import React from "react";
import * as FaIcons from "react-icons/fa";
import * as SiIcons from "react-icons/si";

const iconMapping: { [key: string]: any } = {
    "Node JS": FaIcons.FaNodeJs,
    "React JS": FaIcons.FaReact,
    "Ec2": SiIcons.SiAmazonec2,
    "Lambda": SiIcons.SiAwslambda,
    "Api gateway": SiIcons.SiAmazonapigateway,
    "S3": SiIcons.SiAmazons3,
    "Nginx": SiIcons.SiNginx,
    "Tailwind": SiIcons.SiTailwindcss,
    "Flask": SiIcons.SiFlask,
    "Django": SiIcons.SiDjango,
    "Express": SiIcons.SiExpress,
    "Next": SiIcons.SiNextdotjs,
    "Spring boot": SiIcons.SiSpringboot,
    "spring boot": SiIcons.SiSpringboot,
    "Object Oriented": FaIcons.FaCode,
    "Functional": FaIcons.FaProjectDiagram,
    "Scripting": FaIcons.FaKeyboard,
    "REST API": FaIcons.FaExchangeAlt,
    "Dynamo db": SiIcons.SiAmazondynamodb,
    "Jwt": FaIcons.FaJava,
    "Bootstrap": FaIcons.FaBootstrap,
    "Ci": FaIcons.FaDotCircle,
    "AWS": SiIcons.SiAmazonaws,
    "Serverless": SiIcons.SiServerless,
    "Azure": SiIcons.SiMicrosoftazure,
    "GCP": SiIcons.SiGooglecloud,
    "SwiftUI": FaIcons.FaAppStoreIos,
    "Swift": SiIcons.SiSwift,
    "React Native": FaIcons.FaReact,
    "Flutter": SiIcons.SiFlutter,
    ".NET": SiIcons.SiDotnet,
    "SQL": FaIcons.FaDatabase,
    "MySql": SiIcons.SiMysql,
    "Coredata": SiIcons.SiSwift,
    "Xctests": SiIcons.SiSwift,
    "Widgetkit": SiIcons.SiSwift,
    "Uikit": SiIcons.SiSwift,
    "Git": FaIcons.FaGitAlt,
    "Docker": FaIcons.FaDocker,
    "Github Actions": FaIcons.FaGithub,
    "Linux": FaIcons.FaLinux,
    "Tensorflow": SiIcons.SiTensorflow,
    "Pytorch": SiIcons.SiPytorch,
    "NLP": FaIcons.FaLanguage,
    "Pre-trained models": FaIcons.FaRobot,
    "CV": SiIcons.SiOpencv,
    "Leadership": FaIcons.FaUserTie,
    "Communication": FaIcons.FaComments,
    "Team Work": FaIcons.FaUsers,
    "Agile": SiIcons.SiJira,
    "Management": FaIcons.FaTasks,
    "CI/CD": FaIcons.FaDotCircle,
    "Python": SiIcons.SiPython,
    "Data Analysis": FaIcons.FaChartBar,
    "Image Recognition": FaIcons.FaImage,
    "Networking": FaIcons.FaNetworkWired,
    "Web Scraping": FaIcons.FaSearch,
    "GenAI integration": FaIcons.FaRobot,
    "Google APIs": SiIcons.SiGoogle,
    "Pandas": SiIcons.SiPandas,
    "Neural Networks": FaIcons.FaBrain,
    "Keras": SiIcons.SiKeras,
    "Transfer Learning": FaIcons.FaRobot,
    "LSTM": FaIcons.FaBrain,
    "RNNs": FaIcons.FaNetworkWired,
    "Attention Mechanisms": SiIcons.SiBasicattentiontoken,
    "Beanstalk": FaIcons.FaAws,
    "ASP.NET Core": SiIcons.SiDotnet,
};

export default iconMapping;